import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      colors: {
        hover: '#F1F5F9',
        warning: '#F59E0B',
        'on-tertiary-container': '#ffede6',
        'secondary-container': '#d0e1fb',
        'secondary-fixed': '#d3e4fe',
        'surface-container-highest': '#e1e2ed',
        'on-surface-variant': '#434655',
        secondary: '#505f76',
        'on-surface': '#191b23',
        'surface-container-high': '#e7e7f3',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#38485d',
        'on-primary-container': '#eeefff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-secondary-fixed': '#0b1c30',
        surface: '#FFFFFF',
        'surface-dim': '#d9d9e5',
        'inverse-on-surface': '#f0f0fb',
        'primary-fixed': '#dbe1ff',
        'outline-variant': '#c3c6d7',
        'primary-fixed-dim': '#b4c5ff',
        error: '#ba1a1a',
        'text-primary': '#0F172A',
        'on-secondary-container': '#54647a',
        'on-primary-fixed-variant': '#003ea8',
        'on-secondary': '#ffffff',
        'primary-container': '#2563eb',
        danger: '#EF4444',
        'surface-bright': '#faf8ff',
        'surface-container': '#ededf9',
        primary: '#004ac6',
        'on-error': '#ffffff',
        'tertiary-fixed': '#ffdbcd',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#360f00',
        outline: '#737686',
        'tertiary-fixed-dim': '#ffb596',
        border: '#E2E8F0',
        'surface-container-low': '#f3f3fe',
        'tertiary-container': '#bc4800',
        'inverse-primary': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        background: '#F8FAFC',
        'on-background': '#191b23',
        'secondary-fixed-dim': '#b7c8e1',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'inverse-surface': '#2e3039',
        success: '#10B981',
        'surface-tint': '#0053db',
        selected: '#DBEAFE',
        'surface-variant': '#e1e2ed',
        tertiary: '#943700',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '24px',
        lg: '16px',
        md: '12px',
        sm: '8px',
        huge: '48px',
        unit: '8px',
        xxl: '32px',
        xs: '4px',
      },
    },
  },
  plugins: [],
};
export default config;
